# Generated by Django 3.1.4 on 2021-01-07 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addbike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandname', models.CharField(choices=[('honda', 'honda'), ('royalenfield', 'royalenfield'), ('bmw', 'bmw')], max_length=20)),
                ('brandlogo', models.ImageField(upload_to='brands/')),
                ('bikemodel', models.CharField(choices=[('Spshine', 'Spshine'), ('Hornet', 'Hornet'), ('Xblade', 'Xblade'), ('Navi', 'Navi'), ('Royal Enfield Classic 350', 'Royal Enfield Classic 350'), ('Royal Enfield Himalayan', 'Royal Enfield Himalayan'), ('Royal Enfield Continental GT', 'Royal Enfield Continental GT'), ('Royal Enfield Interceptor 650', 'Royal Enfield Interceptor 650'), ('BMW G310R', 'BMW G310R'), ('BMW S1000 RR', 'BMW S1000 RR'), ('BMW R1250 GS', 'BMW R1250 GS'), ('BMW R nine T', 'BMW R nine T')], max_length=60)),
                ('bikefrontimage', models.ImageField(upload_to='bikes/')),
                ('bikebackimage', models.ImageField(upload_to='bikes/')),
                ('bikeleftimage', models.ImageField(upload_to='bikes/')),
                ('bikerightimage', models.ImageField(upload_to='bikes/')),
                ('bikecost', models.IntegerField()),
                ('bikecc', models.IntegerField()),
                ('fuelinjectiontype', models.CharField(choices=[('bs4', 'bs4'), ('bs6', 'bs6')], max_length=10)),
                ('location', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=32)),
                ('lastname', models.CharField(max_length=32)),
                ('username', models.CharField(max_length=32)),
                ('emailid', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=60)),
                ('pincode', models.IntegerField()),
                ('age', models.IntegerField()),
            ],
        ),
    ]
